main:
    output_folder: ./noisi_output
    stationlist: ./noisi/examples_inv/stationlist_swiss_6.csv 
    add_metadata: false
    add_noise: 1.5
    output_plot: true

project_config:
    project_name: noisi_inv_example 
    synt_data: DIS
    verbose: false
    load_to_memory: true
    compress_output_files: false

data_download:
    download_data: true
    download_data_date: yesterday
    download_data_days: 1
    download_data_channels: ['BHZ']
    
    process_data_win_len: 7200
    process_data_overlap: 100
    
    gcmt_exclude: False

    min_station_dist: 0

    domain_type: circular
    
    circ_lat_center: 46
    circ_lon_center: 8
    circ_radius_min: 0 
    circ_radius_max: 2
    
    rect_lat_min: 30
    rect_lat_max: 50
    rect_lon_min: -10
    rect_lon_max: 30
    

inversion_config:
    observed_corr: null 
    opt_statpair: null 
    snr_thresh: 0
    corr_max_dist: null
    nr_iterations: 1
    nr_step_tests: 5
    step_test_smoothing: false
    frac_corr_slt: 1
    step_length_min: 0.05
    step_length_max: 3.0
    step_smooth: [[2,3],[4,2],[6,1.5],[8,1]] 
    smoothing_cap: 95
    

grid_config:
    grid_dx_in_m: 35000
    grid_lat_max: 65
    grid_lat_min: 30
    grid_lon_max: 25
    grid_lon_min: -15
    
svp_grid_config:
    svp_grid: true
    svp_dense_antipole: false
    svp_only_ocean: true
    svp_voronoi_area: true
    svp_station_remove: 1
    svp_plot: false
    svp_beta:
    - 7
    svp_gamma:
    - 0
    svp_lat_0:
    - 47
    svp_lon_0:
    - 8
    svp_phi_min:
    - 2
    svp_phi_max:
    - 5
    svp_sigma:
    - 10

auto_data_grid_config:
    auto_data_grid: false
    auto_data_path: null
    auto_data_thresh: 0.5
    auto_station_remove: 1
    auto_back_grid_centre: stations
    auto_back_grid_phi_min: 2
    auto_back_grid_phi_max: 4
    auto_data_grid_phi: 1
    auto_data_path: null
    auto_extent:
    - -90
    - 0
    - 0
    - 90
    auto_gamma_thresh: 5
    
wavefield_config:
    wavefield_channel: Z
    wavefield_domain: time
    wavefield_duration: 5000.0
    wavefield_filter: null
    wavefield_path: null
    wavefield_point_force: 1.0e9
    wavefield_sampling_rate: 1.0
    wavefield_type: analytic
    v: 3000.0
    q: 100.0
    rho: 3000.0 
    
source_config:
    get_auto_corr: false
    model_observed_only: true
    max_lag: 1500
    diagonals: false
    rotate_horizontal_components: false

source_setup_config:
    - distribution: homogeneous
      mfp_smooth: 4
      mean_frequency_Hz: 0.15
      standard_deviation_Hz: 0.05
      weight: 1.0
      taper_percent: 1.0
      normalize_spectrum_to_unity: true

measr_config:
    mtype: "ln_energy_ratio"
    taper_perc: 0.01
    bandpass: [[0.01,0.2,5]]
    weights: [1.0]
    g_speed: 2700
    waterlevel_perc: 0
    window_params_wtype: "hann"
    window_params_hw: 30
    window_params_hw_variable: 100
    window_params_win_overlap: false
    window_params_sep_noise: 0.0
    window_plot_measurements: false
    ignore_network: false
